# NumPy Basics <hr style = "border:10px solid#12345678"></hr>

Data Analyst: Ian Patrick M. Alvior <br> Department: Electrical Engineering

Install and update Numpy

In [19]:
#%pip install numpy --upgrade

In [16]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Install and update scipy

In [17]:
#%pip install scipy --upgrade

In [20]:
pip install scipy

   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.0 MB ? eta -:--:--
    --------------------------------------- 0.5/41.0 MB 394.5 kB/s eta 0:01:43
    --------------------------------------- 0.8/41.0 MB 583.4 kB/s eta 0:01:09
    --------------------------------------- 0.8/41.0 MB 583.4 kB/s eta 0:01:09
   - -------------------------------------- 1.0/41.0 MB 533.1 kB/s eta 0:01:15
   - -------------------------------------- 1.3/41.0 MB 612.8 kB/s eta 0:01:05
   - -------------------------------------- 1.6/41.0 MB 673.4 kB/s eta 0:00:59
   - -------------------------------


[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [23]:
# 1-dimensional array
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [25]:
# size of an array
np.shape(array_a)


(3,)

In [22]:
# 1-dimensional array
array_b = np.array([4,5,6])
array_b

array([4, 5, 6])

# 2D Array

In [26]:
# 2-dimensional array
my_array = np.array([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# size of matrix
np.shape(my_array)

(2, 3)

In [29]:
# transpose of a matrix
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
# size of matrix
np.shape(t_array)

(3, 2)

# Measures of Central Tendency

Fruit Price List

In [31]:
# fruit price list dataset
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [33]:
# mean
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [34]:
# median
fruits_median = np.median(fruits)
fruits_median

np.float64(120.0)

In [36]:
# sort
fruits_sorted = np.sort(fruits)
fruits_median

np.float64(120.0)

In [37]:
# mode
stats.mode(fruits)

ModeResult(mode=np.int64(60), count=np.int64(1))

Voltage Response

In [41]:
# voltage response dataset
voltage = np.array([
    [1,2,3,4,5,6,7,8],
    [12,5,9.2,3.3,24,18.9,15.4,np.nan],
    [2.5,4.3,6,9,11.2,14.5,17.8,20]
])
voltage

array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ],
       [12. ,  5. ,  9.2,  3.3, 24. , 18.9, 15.4,  nan],
       [ 2.5,  4.3,  6. ,  9. , 11.2, 14.5, 17.8, 20. ]])

# Measures of Variability

Exam Performance

In [43]:
# exam performance dataset
grade = np.array([9.8,9.4,9.1,8.9,8.8,8.5,8.2,7.8,7.4,7,6.7,3.5])
grade

array([9.8, 9.4, 9.1, 8.9, 8.8, 8.5, 8.2, 7.8, 7.4, 7. , 6.7, 3.5])

Cake Price List

In [47]:
# cake price list dataset
price = np.array([
    [3.3,12,5.3,11.2,10.2,4.5,6.2,6.4,8,9.84],
    [120,420,163.3,72.3,157,64.2,99,100,125,120.2]
])
price

array([[  3.3 ,  12.  ,   5.3 ,  11.2 ,  10.2 ,   4.5 ,   6.2 ,   6.4 ,
          8.  ,   9.84],
       [120.  , 420.  , 163.3 ,  72.3 , 157.  ,  64.2 ,  99.  , 100.  ,
        125.  , 120.2 ]])

Pooled Standard Deviation

In [48]:
# battery life dataset
battery = np.array([
    ['A','A','A','A','A','B','B','B','B','B','C','C','C','C','C'],
    [12.1,12.2,12.3,12.4,12.5,12.6,12.7,12.8,12.9,11,11.1,11.2,11.3,11.4,11.5]
])
battery

array([['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C',
        'C', 'C'],
       ['12.1', '12.2', '12.3', '12.4', '12.5', '12.6', '12.7', '12.8',
        '12.9', '11', '11.1', '11.2', '11.3', '11.4', '11.5']],
      dtype='<U32')